# Generated by Django 3.0.3 on 2020-02-21 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='external_cost_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=40, unique=True)),
                ('price', models.FloatField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='external_cost_stock_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2020-02-21')),
                ('quantity', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='external_cost.external_cost_list')),
            ],
        ),
        migrations.CreateModel(
            name='external_cost_stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(max_length=12)),
                ('value', models.FloatField(max_length=12)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='external_cost.external_cost_list')),
            ],
        ),
    ]
