# Generated by Django 3.0.3 on 2020-02-21 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('external_cost', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='external_cost_expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2020-02-21')),
                ('quantity', models.FloatField(max_length=20)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='external_cost.external_cost_list')),
            ],
        ),
    ]
