# Generated by Django 3.0.3 on 2020-02-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_cost', '0002_external_cost_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='external_cost_expense',
            name='value',
            field=models.FloatField(max_length=20, null=True),
        ),
    ]
