# Generated by Django 3.0.3 on 2020-02-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_cost', '0003_external_cost_expense_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='external_cost_expense',
            name='date',
            field=models.DateField(default='2020-02-22'),
        ),
        migrations.AlterField(
            model_name='external_cost_stock_history',
            name='date',
            field=models.DateField(default='2020-02-22'),
        ),
    ]
