# Generated by Django 3.0.3 on 2020-02-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_cost', '0004_auto_20200222_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='external_cost_expense',
            name='date',
            field=models.DateField(default='2020-02-24'),
        ),
        migrations.AlterField(
            model_name='external_cost_stock_history',
            name='date',
            field=models.DateField(default='2020-02-24'),
        ),
    ]
