# Generated by Django 3.0.3 on 2020-02-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_auto_20200216_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_stock_history',
            name='date',
            field=models.DateField(default='2020-02-18'),
        ),
    ]
