# Generated by Django 3.0.3 on 2020-02-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_auto_20200219_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_stock_history',
            name='date',
            field=models.DateField(default='2020-02-20'),
        ),
    ]
