# Generated by Django 3.0.3 on 2020-02-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_auto_20200220_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_stock_history',
            name='date',
            field=models.DateField(default='2020-02-21'),
        ),
    ]
