# Generated by Django 3.0.3 on 2020-02-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_auto_20200221_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_stock_history',
            name='date',
            field=models.DateField(default='2020-02-22'),
        ),
    ]
