# Generated by Django 3.0.3 on 2020-02-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_cost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra_cost',
            name='date',
            field=models.DateField(default='2020-02-22'),
        ),
    ]
