# Generated by Django 3.0.3 on 2020-02-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_cost', '0003_auto_20200224_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra_cost',
            name='date',
            field=models.DateField(default='2020-02-25'),
        ),
    ]
