# Generated by Django 3.0.3 on 2020-02-05 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='raw_material_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=40)),
                ('price', models.FloatField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='raw_material_stock_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raw_materials.raw_material_list')),
            ],
        ),
        migrations.CreateModel(
            name='raw_material_stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(max_length=12)),
                ('value', models.FloatField(max_length=12)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raw_materials.raw_material_list')),
            ],
        ),
    ]
