# Generated by Django 3.0.3 on 2020-02-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0002_auto_20200205_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raw_material_list',
            name='item',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='raw_material_stock_history',
            name='date',
            field=models.DateField(default='2020-02-06'),
        ),
    ]
