# Generated by Django 3.0.3 on 2020-02-12 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0004_auto_20200212_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='retail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2020-02-12')),
                ('quantity', models.IntegerField()),
                ('value', models.FloatField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='saleman_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('commision', models.FloatField(max_length=5)),
                ('mobile', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='saleman_sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2020-02-12')),
                ('quantity', models.IntegerField()),
                ('value', models.FloatField(max_length=20)),
                ('after_commission_value', models.FloatField(max_length=20)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.saleman_list')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.product_list')),
            ],
        ),
        migrations.AddField(
            model_name='saleman_list',
            name='product',
            field=models.ManyToManyField(through='sales.saleman_sale', to='production.product_list'),
        ),
        migrations.CreateModel(
            name='retail_sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('product', models.ManyToManyField(through='sales.retail', to='production.product_list')),
            ],
        ),
        migrations.AddField(
            model_name='retail',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.retail_sales'),
        ),
        migrations.AddField(
            model_name='retail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.product_list'),
        ),
        migrations.CreateModel(
            name='pay_saleman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2020-02-12')),
                ('amount', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.saleman_list')),
            ],
        ),
        migrations.CreateModel(
            name='deposit_from_saleman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2020-02-12')),
                ('amount', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.saleman_list')),
            ],
        ),
    ]
