# Generated by Django 3.0.3 on 2020-02-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20200212_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='retail_sales',
            name='date',
            field=models.DateField(default='2020-02-16'),
        ),
        migrations.AlterField(
            model_name='deposit_from_saleman',
            name='date',
            field=models.DateField(default='2020-02-16'),
        ),
        migrations.AlterField(
            model_name='pay_saleman',
            name='date',
            field=models.DateField(default='2020-02-16'),
        ),
        migrations.AlterField(
            model_name='retail',
            name='date',
            field=models.DateField(default='2020-02-16'),
        ),
        migrations.AlterField(
            model_name='saleman_sale',
            name='date',
            field=models.DateField(default='2020-02-16'),
        ),
    ]
