# Generated by Django 3.0.3 on 2020-02-18 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20200216_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='pay_retail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2020-02-18')),
                ('amount', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.saleman_list')),
            ],
        ),
        migrations.AlterField(
            model_name='deposit_from_saleman',
            name='date',
            field=models.DateField(default='2020-02-18'),
        ),
        migrations.AlterField(
            model_name='retail',
            name='date',
            field=models.DateField(default='2020-02-18'),
        ),
        migrations.AlterField(
            model_name='retail_sales',
            name='date',
            field=models.DateField(default='2020-02-18'),
        ),
        migrations.AlterField(
            model_name='saleman_sale',
            name='date',
            field=models.DateField(default='2020-02-18'),
        ),
        migrations.DeleteModel(
            name='pay_saleman',
        ),
    ]
