# Generated by Django 3.0.3 on 2020-02-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20200219_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit_from_saleman',
            name='date',
            field=models.DateField(default='2020-02-20'),
        ),
        migrations.AlterField(
            model_name='pay_retail',
            name='date',
            field=models.DateField(default='2020-02-20'),
        ),
        migrations.AlterField(
            model_name='retail',
            name='date',
            field=models.DateField(default='2020-02-20'),
        ),
        migrations.AlterField(
            model_name='retail_sales',
            name='date',
            field=models.DateField(default='2020-02-20'),
        ),
        migrations.AlterField(
            model_name='saleman_sale',
            name='date',
            field=models.DateField(default='2020-02-20'),
        ),
    ]
