# Generated by Django 3.0.3 on 2020-02-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_auto_20200220_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit_from_saleman',
            name='date',
            field=models.DateField(default='2020-02-21'),
        ),
        migrations.AlterField(
            model_name='pay_retail',
            name='date',
            field=models.DateField(default='2020-02-21'),
        ),
        migrations.AlterField(
            model_name='retail',
            name='date',
            field=models.DateField(default='2020-02-21'),
        ),
        migrations.AlterField(
            model_name='retail_sales',
            name='date',
            field=models.DateField(default='2020-02-21'),
        ),
        migrations.AlterField(
            model_name='saleman_sale',
            name='date',
            field=models.DateField(default='2020-02-21'),
        ),
    ]
